### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [6]:
import numpy as np
import random

In [35]:
vector = np.array([random.uniform(0, 1) for i in range(10)])
print(vector)
vector.shape

[0.59781536 0.33279144 0.9874878  0.11124008 0.17663585 0.45997384
 0.84337955 0.28310269 0.1840089  0.614722  ]


(10,)

In [22]:
vector = np.random.rand(10)
vector
vector.shape

(10,)

In [16]:
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])
print(matrix)
matrix.shape

[[11 14 17]
 [20 23 26]
 [29 32 35]]


(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [23]:
vector_ = np.round(vector + 10, 2)
print(vector_)

[10.99 10.23 10.07 10.06 10.2  10.46 10.54 10.36 10.33 10.81]


In [24]:
matrix_ = matrix * 2
print(matrix_)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [25]:
vector_ = vector ** 2
print(vector_)

[0.97570471 0.05134524 0.00462996 0.00340156 0.04069645 0.21460291
 0.28897616 0.12726413 0.10905727 0.66188261]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [27]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [29]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [31]:
# результат буде 2*1:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [32]:
# 2*2
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [33]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [36]:
vector.T # нічого не змінилося

array([0.59781536, 0.33279144, 0.9874878 , 0.11124008, 0.17663585,
       0.45997384, 0.84337955, 0.28310269, 0.1840089 , 0.614722  ])

In [38]:
column_vector = np.expand_dims(vector, axis=1)
column_vector ## вектор-рядок змінився на вектор-стовпець

array([[0.59781536],
       [0.33279144],
       [0.9874878 ],
       [0.11124008],
       [0.17663585],
       [0.45997384],
       [0.84337955],
       [0.28310269],
       [0.1840089 ],
       [0.614722  ]])

In [41]:
column_vector.shape

(10, 1)

In [39]:
column_vector.T

array([[0.59781536, 0.33279144, 0.9874878 , 0.11124008, 0.17663585,
        0.45997384, 0.84337955, 0.28310269, 0.1840089 , 0.614722  ]])

In [40]:
column_vector.T.shape

(1, 10)