# Homework: Numpy

In [1]:
import numpy as np

C:\Users\Admin\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
C:\Users\Admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
np

<module 'numpy' from 'C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

## Task 1

In [13]:
arr = np.array([5, 15, 25, 35, 45])
print(arr)
zeros = np.zeros(7)
print(zeros)
ones = np.ones(6)
print(ones)
arr2 = np.arange(10, 20)
print(arr2)

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]


## Task 2

In [20]:
arr = np.array([12, 24, 36, 48, 60])
print(arr)

mult = arr * 2
print("multiplied by 2:", mult)

add = arr + 10
print("added 10:", add)

square = arr ** 2
print("squared elements:", square)

sqrt = np.sqrt(arr)
print("square root:", sqrt)

[12 24 36 48 60]
multiplied by 2: [ 24  48  72  96 120]
added 10: [22 34 46 58 70]
squared elements: [ 144  576 1296 2304 3600]
square root: [3.46410162 4.89897949 6.         6.92820323 7.74596669]


## Task 3

In [23]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(data)

mean = np.mean(data)
print("mean:", mean)

min_v = np.min(data)
print("minimum:", min_v)

max_v = np.max(data)
print("maximum:", max_v)

sum_v = np.sum(data)
print("sum:", sum_v)

[18 27 33 41 52 68 79]
mean: 45.42857142857143
minimum: 18
maximum: 79
sum: 318


## Task 4

In [25]:
arr = np.array([15, 22, 35, 44, 58, 6])
print(arr)

[15 22 35 44 58  6]


In [29]:
first = arr[0]
print("first element:", first)

last = arr[-1]
print("last element:", last)

slice_el = arr[1:4]
print("elements at indices 1 to 3:", slice_el)

grater_40 = arr[arr > 40]
print("elements grater than 40:", grater_40)

first element: 15
last element: 6
elements at indices 1 to 3: [22 35 44]
elements grater than 40: [44 58]


## Task 5

In [39]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

print(matrix.shape)
print(matrix[0, :])
print(matrix[:, 1])
summ = np.sum(matrix)
print(summ)
mean = np.mean(matrix)
print(mean)

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
